---
name: scry
networks:
  scry-network:
volumes:
  # Shared tmpfs
  scry-logs:
    driver_opts:
      device: shm
      type: tmpfs
      o: "size=256m"
  grafana:
  victoria:
services:
  syslogng:
    build: ./syslogng
    ports:
      - "0.0.0.0:514:514/udp"
      - "0.0.0.0:514:514/tcp"
      - "0.0.0.0:601:601/tcp"
      - "0.0.0.0:6514:6514/tcp"
    networks:
      - scry-network
    volumes:
      - scry-logs:/var/log/remote
  promtail:
    build: ./promtail
    networks:
      - scry-network
    volumes:
      - scry-logs:/var/log/scrape
    ports:
      - "0.0.0.0:9080:9080/tcp"
    command:
      [
        "-config.file=/etc/promtail/config.yml"
      ]
  loki:
    build: ./loki
    ports:
      - "0.0.0.0:3100:3100"
    networks:
      - scry-network
  grafana:
    build: ./grafana
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - scry-network
  victoria:
    build: ./victoria
    command:
      [
        "--promscrape.config=/promscrape.config"
      ]
    ports:
      - "0.0.0.0:8428:8428/tcp"
    volumes:
      - victoria:/victoria-metrics-data
    networks:
      - scry-network
  vmalert:
    build: ./vmalert
    command:
      [
        "-rule=alerts.yml",
        "-datasource.url=http://victoria:8428",
        "-notifier.url=http://alertmanager:9093",
        "-remoteWrite.url=http://victoria:8428",
        "-remoteRead.url=http://victoria:8428"
      ]
    ports:
      - "0.0.0.0:8880:8880/tcp"
    networks:
      - scry-network
  gnmic:
    build: ./gnmic
    ports:
      - "0.0.0.0:9081:9081/tcp"
    networks:
      - scry-network
  alertmanager:
    build: ./alertmanager
    ports:
      - "0.0.0.0:9093:9093/tcp"
    networks:
      - scry-network
