---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslogng
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslogng
          __path__: /var/log/scrape/*.json
    pipeline_stages:
      - labeldrop:
          - filename
      - json:
          expressions:
            priority: PRIORITY
      - labels:
          priority:
      - regex:
          source: priority
          expression: (?P<err>notice)
      - labels:
          err:
      - metrics:
          err:
            type: Counter
            source: err
            config:
              action: inc
            prefix: syslogng_
            description: "Counter for logs with priority 'notice' or 'info'"
            max_idle_duration: 48h
